Fix a common crash due to missing cortical interstitium segmentation
Traceback (most recent call last):
  File "M:\Histo\BANFF-AID\banff_aid\cli\BanffAid\BanffAid.py", line 35, in <module>
    main()
  File "M:\Histo\BANFF-AID\banff_aid\cli\BanffAid\BanffAid.py", line 31, in main
    bls.main()
  File "M:\Histo\BANFF-AID\banff_aid\cli\BanffAid\banff_lesion_score\banff_lesion_score.py", line 678, in main
    report_path = self.generate_report()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\banff_aid\cli\BanffAid\banff_lesion_score\banff_lesion_score.py", line 622, in generate_report
    ci_results = self.compute_ci()
                 ^^^^^^^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\banff_aid\cli\BanffAid\banff_lesion_score\banff_lesion_score.py", line 230, in compute_ci
    q2 = np.quantile(pruned_edges, q=0.5)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\.venv\Lib\site-packages\numpy\lib\function_base.py", line 4543, in quantile
    return _quantile_unchecked(
           ^^^^^^^^^^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\.venv\Lib\site-packages\numpy\lib\function_base.py", line 4555, in _quantile_unchecked
    return _ureduce(a,
           ^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\.venv\Lib\site-packages\numpy\lib\function_base.py", line 3823, in _ureduce
    r = func(a, **kwargs)
        ^^^^^^^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\.venv\Lib\site-packages\numpy\lib\function_base.py", line 4722, in _quantile_ureduce_func
    result = _quantile(arr,
             ^^^^^^^^^^^^^^
  File "M:\Histo\BANFF-AID\.venv\Lib\site-packages\numpy\lib\function_base.py", line 4831, in _quantile
    slices_having_nans = np.isnan(arr[-1, ...])
                                  ~~~^^^^^^^^^
IndexError: index -1 is out of bounds for axis 0 with size 0